### PR TITLE
Fix warnings on PHP7.3

### LINKED ISSUE #5: Warning on PHP 7.3
I updated my dev machine to PHP 7.3 and now I'm starting to see these errors thrown from this plugin:

```
 Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in (...)/wp-content/plugins/wp-user-signups/wp-signups/includes/functions/admin.php on line 279
```
There are a couple of them, and it seems the fix would be as easy as replacing `continue` with `break`

### PR DESCRIPTION
**Pull request by Biont**
Fix #5 by replacing `continue` with `break` in switch statement.

### CODE REVIEW

**Comment by Biont** [comment]
@JJJ Can you please have a look at this? PHP7.3 adoption is growing every day.

**Comment by JJJ** [comment]
Hi there! Thanks for the PR. I think these should be `continue 1;` instead? Or maybe `break 1;` if that’s what 7.3 now requires.

We don’t want to break out of the foreach/switch entirely, we simply want to continue iterating over the remaining signup IDs.

**Comment by Biont** [comment]
Hi @JJJ thanks for your comment. I looked at the code again and from my understanding, there should be no problem. I did not touch the `foreach` loops within the first couple of switch cases, just the `continue`-statements at the end of a switch case (-> the ones that prevent the case from "falling through" to the next one)

I'm not sure, but it could be that the warning message is a bit misleading here:
```
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in (...)/wp-content/plugins/wp-user-signups/wp-signups/includes/functions/admin.php on line 279
```

I guess it should be read as 

```
Hey you used 'continue' when you'd normally 'break' on this line. There's probably an intention behind that and my best guess is that we're currently in a loop. If so, let me suggest a statement that would actually affect a hypothetical outer loop: ' continue 2;' 
```

But since the switch-statement itself is not in a loop, we can simply replace it with `break` to fix that warning.

**Comment by tyrann0us** [comment]
@JJJ, can you please take a look at what @Biont wrote? PHP 7.3 was released half a year ago and this bug has prevented us from updating our systems since then. It should not be a big effort to test and merge the PR.

Thanks!

**Comment by JJJ** [comment]
In my opinion, these warnings are pretty dumb and PHP 7.3 is interpreting these as warnings incorrectly.

https://www.php.net/manual/en/control-structures.continue.php

The PHP team claims this deprecation is to fix accidental issues from switch statements inside of loops, but in our case here we have a loop inside a switch statement that is erroneously showing warnings.

1. The switch statement decides what code to execute.
1. The code that gets executed is a loop.
1. The loop has checks to continue iterating and skip further processing inside it.

`continue` is supposed to be silently equivalent to `continue 1;` which is what we want; to continue looping.

`break` will cause the code to exit the `foreach` loop completely, which is not what we want.

The PR is not correct, and if I'm reading and understanding the PHP spec, there simply isn't a way to write this kind of code anymore.

Perhaps `continue 1;` is explicit enough to silence the warning, but I could not find anything in the PHP documentation that clearly communicated that.

**Comment by Biont** [comment]
Hey @JJJ thanks for having another look.

I just went through and double-checked all the 3 affected lines of this PR and none of them changes a `continue` statement inside a for-loop. This is not what PHP is complaining about. 

[The first 2 break out of the same switch/case block](https://github.com/stuttter/wp-user-signups/blob/e7b2b404b562e8b7f2af9741da28b3091bbfc50c/wp-signups/includes/functions/admin.php#L288-L311)
example 1

[The third one breaks a separate switch/case block](https://github.com/stuttter/wp-user-signups/blob/e7b2b404b562e8b7f2af9741da28b3091bbfc50c/wp-signups/includes/functions/admin.php#L314-L330)
example 2

These lines have been "wrong" all the time (because `continue` is used instead of `break` inside a switch/case), PHP just did not complain until 7.3.

**Comment by JJJ** [comment]
I merged this, but I still do not understand it 😁 and cannot find any evidence on php.net that this change is how Switch statements are expected to work going forward.

https://www.php.net/manual/en/control-structures.switch.php

> Note that unlike some other languages, the continue statement applies to switch and acts similar to break. If you have a switch inside a loop and wish to continue to the next iteration of the outer loop, use continue 2.

That still isn’t what is happening in this code, so why would PHP complain? The break is inside an if, not a loop, and that appears to be allowed without warning as documented.

I’m shocked I haven’t used this pattern more in other places, because it’s definitely the style of code I write, and after doing a bunch of research into 7.3 changes, I see no reason why this code would trigger warnings.

The original break statements are functionally equivalent to continue. They aren’t in a loop. They both break out of the Switch statement. It seems very wrong to need to change this, but I don’t want for this to cause anyone any problems either. 🤣

**Comment by Biont** [comment]
For reference, here is the [php 7.3 migration document](https://www.php.net/manual/en/migration73.incompatible.php) describing the introduction of this warning.

Thank you for merging this @JJJ

**Comment by JJJ** [comment]
Thanks @Biont. I'd found that document as well. Still seems like it reads as if either could be used.

But... clearly that isn't the case! So I'll avoid using it in the future. Thanks again!

**Comment by joehoyle** [comment]
Hey @JJJ, hope you are well! I wondered if you are still planning to tag the versions, so these released go to packagist too? Thanks!

**Comment by JJJ** [comment]
> I wondered if you are still planning to tag the versions, so these released go to packagist too? Thanks!

Just tagged 5.0.0. Should go to packagist shortly.

Very sorry for the delay everyone, and thank you @joehoyle for the nudge.

**Comment by joehoyle** [comment]
Great, thanks @JJJ

**Pull request merged**
